// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_linear_kernel();
RcppExport SEXP _rcpp_module_boot_sqr_exponential_kernel();
RcppExport SEXP _rcpp_module_boot_sqr_exponential_ard_kernel();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_linear_kernel", (DL_FUNC) &_rcpp_module_boot_linear_kernel, 0},
    {"_rcpp_module_boot_sqr_exponential_kernel", (DL_FUNC) &_rcpp_module_boot_sqr_exponential_kernel, 0},
    {"_rcpp_module_boot_sqr_exponential_ard_kernel", (DL_FUNC) &_rcpp_module_boot_sqr_exponential_ard_kernel, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_kl_diff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
